(defun rgbToGrayscale (rgbArray)
  (setf size (length rgbArray))
  (setf count 0)
  (dotimes (x (/ size 3))
    (setf newRed (* (aref rgbArray (+ 0 count)) .21))
    (setf newGreen (* (aref rgbArray (+ 1 count)) .72))
    (setf newBlue (* (aref rgbArray (+ 2 count)) .07))
    (setf newVal (floor (+ (+ newRed newGreen) newBlue)))
    (setf (aref rgbArray (+ 0 count)) newVal) 
    (setf (aref rgbArray (+ 1 count)) newVal) 
    (setf (aref rgbArray (+ 2 count)) newVal) 
    (setf count (+ 3 count))
    )
)
